### ISSUE TITLE
下载链接404,科学都不行

### ISSUE THREAD

**Issue by 1393037860** [OneCodeMonkey/music-sources#1]
![image](https://github.com/OneCodeMonkey/music-sources/assets/74531495/778479ea-2f2f-411b-abe7-cd00f16fa261)

**Comment by Bryce-Loski** [comment]
安装git.  直接clone下来

**Comment by OneCodeMonkey** [comment]
> ![image](https://user-images.githubusercontent.com/74531495/277258341-778479ea-2f2f-411b-abe7-cd00f16fa261.png)

已更新
